display_name: BaytBeam
packager: BaytBeam Project
packagerEmail: baytbeam-project@users.noreply.github.com
url: https://github.com/Romany-Osama/localsend
buildArch: x86_64
license: Apache-2.0

icon: assets/img/logo-512.png

requires:
  - libappindicator
  - xdg-user-dirs

keywords:
  - Sharing
  - LAN
  - Files

generic_name: An open source LAN-only home hub based on LocalSend
summary: Share files, chat, and stream over your home LAN with BaytBeam
group: Applications/Utilities

categories:
  - GTK
  - FileTransfer
  - Utility

startup_notify: true
